apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  namespace: sandbox
  labels:
    app: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-green
      namespace: sandbox
  labels:
  template:
    metadata:
      labels:
        app: nginx-green
        namespace: sandbox
    spec:
      containers:
        - name: nginx
          image: nginx:1.11
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 0.5
              memory: 128Mi
            requests:
              cpu: 0.25
              memory: 64Mi
