apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: sandbox
spec:
  selector:
    app: hello-python
    namespace: sandbox
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: hello-python
      namespace: sandbox
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
        namespace: sandbox
    spec:
      containers:
      - name: hello-python
        image: mamercad/hello-python:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
