---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox

---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: sandbox
spec:
  selector:
    app: hello
    namespace: sandbox
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: hello
      namespace: sandbox
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        namespace: sandbox
    spec:
      containers:
      - name: hello
        image: mamercad/hello:blue
        # imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 0.5
            memory: 128Mi
          requests:
            cpu: 0.25
            memory: 64M
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 1
