apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: sandbox
spec:
  type: LoadBalancer
  selector:
    app: nginx-green
    namespace: sandbox
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
