---
- name: playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: ping
      ansible.builtin.ping:

    - name: debug
      ansible.builtin.debug:
        msg: |-
          ::notice::This is a notice message

    - name: summary
      ansible.builtin.blockinfile:
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_STEP_SUMMARY') }}"
        marker: ""
        block: |-
          # Hello from Ansible
          This is coming from Ansible using `ansible.builtin.blockinfile` like this:
          ```yaml
          - name: summary
            ansible.builtin.blockinfile:
              path: "{{ '{{' lookup('ansible.builtin.env', 'GITHUB_STEP_SUMMARY') '}}' }}"
              marker: ""
              block: |-
                # Hello from Ansible
                This is coming from Ansible using `ansible.builtin.blockinfile` like this:
          ```

    - name: more summary
      ansible.builtin.blockinfile:
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_STEP_SUMMARY') }}"
        marker: ""
        block: |-
          ## Another play from Ansible
          Here's more stuff from the next play.
