---
- name: playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: level
      ansible.builtin.lineinfile:
        state: present
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_ENV') }}"
        line: ANNOTATION_1_LEVEL="notice"

    - name: message
      ansible.builtin.lineinfile:
        state: present
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_ENV') }}"
        line: ANNOTATION_1_MESSAGE="this is message 1"

    - name: level
      ansible.builtin.lineinfile:
        state: present
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_ENV') }}"
        line: ANNOTATION_2_LEVEL="warning"

    - name: message
      ansible.builtin.lineinfile:
        state: present
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_ENV') }}"
        line: ANNOTATION_2_MESSAGE="this is message 2"

    - name: level
      ansible.builtin.lineinfile:
        state: present
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_ENV') }}"
        line: ANNOTATION_3_LEVEL="error"

    - name: message
      ansible.builtin.lineinfile:
        state: present
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_ENV') }}"
        line: ANNOTATION_3_MESSAGE="this is message 3"

    - name: message
      ansible.builtin.lineinfile:
        state: present
        path: "{{ lookup('ansible.builtin.env', 'GITHUB_ENV') }}"
        line: ANNOTATION_COUNT=3
