name: ansible

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ansible
  cancel-in-progress: true

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  ansible:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mamercad/sandbox:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "::notice::This is a notice message"
          echo "::warning::This is a warning message"
          echo "::debug::This is a debug message"
          echo "::error::This is a error message"

      - name: ansible
        id: ansible
        working-directory: ansible
        run: |
          ansible-playbook --inventory localhost, --connection local playbook.yml --verbose
