name: ansible2

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ansible
  cancel-in-progress: true

env:
  ANSIBLE_FORCE_COLOR: true
  ANSIBLE_STDOUT_CALLBACK: yaml

jobs:
  ansible:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mamercad/sandbox:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      # - run: |
      #     echo "::notice::This is a notice message"
      #     echo "::warning::This is a warning message"
      #     echo "::debug::This is a debug message"
      #     echo "::error::This is a error message"

      - name: Set the value in bash
        id: step_one
        run: |
          echo 'X<<EOF' >> $GITHUB_ENV
          echo 'this is line 1' >> $GITHUB_ENV
          echo 'this is line 2' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Set the value in bash
        id: step_two
        run: |
          echo $X

      # - name: Ⓐnsible
      #   id: ansible
      #   working-directory: ansible
      #   run: |
      #     ansible-playbook --inventory localhost, --connection local \
      #       playbook.yml --verbose

      # - run: |
      #     echo "::notice::Ansible set FOO=${{ env.FOO }}"
