name: ansible

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ansible
  cancel-in-progress: true

env:
  ANSIBLE_FORCE_COLOR: true
  ANSIBLE_STDOUT_CALLBACK: yaml

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ⓐnsible
        id: ansible
        working-directory: ansible
        run: |
          ansible-playbook --inventory localhost, --connection local \
            playbook.yml --verbose

      - name: annotations
        id: annotations
        run: |
          cat $GITHUB_ENV
          for i in $(seq $ANNOTATION_COUNT); do
            ANNOTATION_LEVEL="ANNOTATION_${i}_LEVEL"
            ANNOTATION_MESSAGE="ANNOTATION_${i}_MESSAGE"
            echo "::${!ANNOTATION_LEVEL:1:-1}::${!ANNOTATION_MESSAGE:1:-1}"
          done
