---
name: awx

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: awx
  cancel-in-progress: true

env:
  ANSIBLE_FORCE_COLOR: true
  ANSIBLE_STDOUT_CALLBACK: unixy

jobs:
  awx:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: python
        run: |
          pip install ansible

      - name: Ⓐnsible
        id: awx
        working-directory: awx
        run: |
          ansible-playbook \
            --inventory localhost, \
            --connection local \
              deploy.yml
        env:
          TOWER_HOST: ${{ secrets.TOWER_HOST }}
          TOWER_USERNAME: ${{ secrets.TOWER_USERNAME }}
          TOWER_PASSWORD: ${{ secrets.TOWER_PASSWORD }}
