---
name: docker

on:
  pull_request:
  push:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: docker
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          docker --version
