---
name: docker

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        run: |
          docker --version
