---
name: docker

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        run: |
          docker --version
          docker run --rm --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:rw centos:7 systemctl list-units
