---
name: packer

on:
  pull_request:
  push:
    branches:
      - packer
  workflow_dispatch:

concurrency:
  group: packer
  cancel-in-progress: true

jobs:
  packer:
    # runs-on: ubuntu-latest
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.5.6" # or `latest`

      - name: Run `packer validate`
        id: validate
        run: "packer validate st2.json"

      - name: Run `packer build`
        id: build
        run: "packer build st2.json"
