name: pr-revert

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJSON(github) }}"
