name: pr-revert

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Revert
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "::group::Revert PR initiated from the GH/GHE UI"
          if [[ "${{ github.head_ref }}" =~ ^revert\-([0-9]+)\-.+$ ]]; then
            revert_pr="${BASH_REMATCH[1]}"
            base_sha="${{ github.event.pull_request.base.sha }}"
            gh pr review ${{ github.event.number }} --approve
            gh pr comment ${{ github.event.number}} \
              --body "Auto-approved this revert of PR #${revert_pr} ${base_sha}"
            echo "has-auto-approved=true" >>$GITHUB_OUTPUT
          fi
          echo "::endgroup::"

          echo "::group::Revert PR initiated from default 'git revert'"
          # https://github.com/git/git/blob/69c786637d7a7fe3b2b8f7d989af095f5f49c3a8/sequencer.c#L2255
          if [[ "${{ github.event.pull_request.title }}" =~ ^Revert ]]; then
            base_sha="${{ github.event.pull_request.base.sha }}"
            gh pr review ${{ github.event.number }} --approve
            gh pr comment ${{ github.event.number}} \
              --body "Auto-approved this revert of ${base_sha}"
            echo "has-auto-approved=true" >>$GITHUB_OUTPUT
          fi
          echo "::endgroup::"
