name: pr-revert

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJSON(github) }}"

  logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [[ "${{ github.head_ref }}" =~ ^revert\-([0-9]+)\-.+$ ]]; then
            revert_pr="${BASH_REMATCH[1]}"
            gh pr review ${{ github.event.number }} --approve
            gh pr comment ${{ github.event.number}} --body "Auto-approved this revert of PR #${revert_pr}"
          else
            echo "This is not a revert PR"
          fi
