name: pr-revert

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJSON(github) }}"

  logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [[ "${{ github.head_ref }}" =~ ^revert\-[0-9]+\-.+$ ]]; then
            echo "This is a Revert PR"
            sleep 300
            gh pr checks ${{ github.event.number }}
          else
            echo "This is not a Revert PR"
          fi
