name: pr-revert

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Revert
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # case insensitive regex
          shopt -s nocasematch

          # https://docs.github.com/en/actions/learn-github-actions/expressions#contains
          pr_title_contains_revert="${{ contains(github.event.pull_request.title, 'revert') }}"

          echo "has-auto-approved=false" >>$GITHUB_OUTPUT

          if [[ "${{ github.head_ref }}" =~ ^revert\-([0-9]+)\-.+$ ]]; then
            echo "::group::Revert PR initiated from the GH/GHE UI"
            revert_pr="${BASH_REMATCH[1]}"
            base_sha="${{ github.event.pull_request.base.sha }}"
            gh pr review ${{ github.event.number }} --approve
            gh pr comment ${{ github.event.number}} \
              --body "Auto-approved this revert of PR #${revert_pr} ${base_sha}"
            echo "has-auto-approved=true" >>$GITHUB_OUTPUT
            echo "Auto-approved this revert PR" >>$GITHUB_STEP_SUMMARY
            echo "::endgroup::"
            exit 0

          elif [[ "${{ github.head_ref }}" =~ revert ]]; then
            echo "::group::Revert initiated from branch with 'revert' in name"
            base_sha="${{ github.event.pull_request.base.sha }}"
            gh pr review ${{ github.event.number }} --approve
            gh pr comment ${{ github.event.number}} \
              --body "Auto-approved this revert of ${base_sha}"
            echo "has-auto-approved=true" >>$GITHUB_OUTPUT
            echo "Auto-approved this revert PR" >>$GITHUB_STEP_SUMMARY
            echo "::endgroup::"
            exit 0

          elif [[ "${pr_title_contains_revert}" == "true" ]]; then
            echo "::group::Revert initiated from 'revert' in title"
            base_sha="${{ github.event.pull_request.base.sha }}"
            gh pr review ${{ github.event.number }} --approve
            gh pr comment ${{ github.event.number}} \
              --body "Auto-approved this revert of ${base_sha}"
            echo "has-auto-approved=true" >>$GITHUB_OUTPUT
            echo "Auto-approved this revert PR" >>$GITHUB_STEP_SUMMARY
            echo "::endgroup::"
            exit 0
          fi

          echo "This PR does did not match auto-approval cases" >>$GITHUB_STEP_SUMMARY
