name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: |
        pip install --upgrade pip
        pip install coverage flake8 pre-commit pytest
    - uses: pre-commit/action@v3.0.0
