name: tag

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  foo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJSON(github.ref) }}"
