name: testing

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - open
      - closed
      - reopened
      - synchronize
  workflow_dispatch:

jobs:

  foo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJSON(github) }}"

  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget --quiet --continue https://github.com/cli/cli/releases/download/v2.14.4/gh_2.14.4_linux_amd64.deb
          wget --quiet --continue https://github.com/cli/cli/releases/download/v2.14.4/gh_2.14.4_checksums.txt
          sha256sum --check --ignore-missing gh_2.14.4_checksums.txt
          touch somefile-
          git config --global user.name "GitHub Actions"
          git config --global user.email "github+actions@exmaple.com"
          git checkout -b ci-${{ github.run_number }}
          mkdir tmp 2>/dev/null
          date >tmp/ci-${{ github.run_number }}
          git add tmp/ci-${{ github.run_number }}
          git commit -m "Changes from ci-${{ github.run_number }}"
          git push --set-upstream origin ci-${{ github.run_number }}
          # gh pr create --title "This is the PR title" --body "This is the PR body"
          gh pr create --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
