name: testing1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo testing1
      - uses: ./.github/actions/action1.yml@main
