name: testing1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  testing1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo testing1
      -  uses: mamercad/sandbox/action1@main
