name: json matrix

on:
  push:
    branches:
      - json

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: matrix
        id: matrix
        run: |
          echo 'matrix={"foo":[1,2,3],"bar":[1,2]}' >>$GITHUB_OUTPUT

  next:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: next
        id: next
        run: |
          echo '${{ matrix.foo }} ${{ matrix.bar }}'
