name: testing

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - open
      - closed
      - reopened
      - synchronize

jobs:

  foo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJSON(github) }}"
