name: testing3

on:
  push:
    branches:
      - json

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: matrix
        id: matrix
        run: |
          echo 'matrix={"version":[1,2,3],"release":["1"]}' >>$GITHUB_OUTPUT

  next:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: next
        id: next
        run: |
          echo '${{ matrix.version }} ${{ matrix.release }}'
